# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/msm8917-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),j4primelte j4corelte j6primelte)

endif
